import Head from 'next/head'
import Image from 'next/image'
import Chat from '../components/Chat';
import Sidebar from '../components/Sidebar';

export default function Home() {
  return (
    <div className="bg-gray-300 h-screen justify-center items-center flex">
      <Head>
        <title>Whatsapp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icon.png" />
      </Head>

      <div className="bg-gray-100 flex flex-row w-11/12 h-5/6 shadow-neutral-600 shadow-lg -mt-12">
        <Sidebar/>
        <Chat receiver= {false} />
        
      </div>
    </div>
  );
}
